refactor
Junbo-Zheng/pyextract pull request #12
Opened 2023-06-28 13:57 UTC by nowhszh

1. 放弃使用全局变量
2. 封装复用日志处理代码
3. 高亮关键日志
4. 添加错误返回值检查，异常终止

2023-06-28 14:49 UTC, nowhszh commented on pyextract.py
> +def CHECK_EXIST(ret):
error function name

2023-06-28 15:27 UTC, Junbo-Zheng requested changes
@nowhszh Please update README.md too.

2023-06-28 15:43 UTC, Junbo-Zheng commented on pyextract.py
> +    source_path = '~/Downloads'
```suggestion
    source_path = "~/Downloads"
```

2023-06-28 15:50 UTC, Junbo-Zheng commented on pyextract.py
> +            help='purge source file if is true',
```suggestion
            help="purge source file if is true",
```

2023-06-28 15:50 UTC, Junbo-Zheng commented on pyextract.py
>              help='filter the files to be merged')
```suggestion
            help="filter the files to be merged")
```

2023-06-28 15:57 UTC, Junbo-Zheng commented on pyextract.py
> +        # if exists output path, clear
```suggestion
        # if output path exists, clear
```

2023-06-28 15:57 UTC, Junbo-Zheng commented on pyextract.py
> +    def clear_output_dir(self, ask=True):
```suggestion
    def clear_output_dir(self, cover=True):
```

2023-06-28 15:57 UTC, Junbo-Zheng commented on pyextract.py
> +        if ask:
```suggestion
        if cover:
```

2023-06-28 15:58 UTC, Junbo-Zheng commented on pyextract.py
> +        print(Highlight.Convert("pull") + " %s from %s" % (result, self.__cli_parser.source_path[0]))
move to after line 138

2023-06-28 16:05 UTC, Junbo-Zheng commented on pyextract.py
> +    def merge_logfiles(self):
```suggestion
    # merge all files into a new file
    def merge_logfiles(self):
```

2023-06-28 16:26 UTC, nowhszh commented on pyextract.py
> +    def clear_output_dir(self, ask=True):
Why is this modified

2023-06-29 04:43 UTC, Junbo-Zheng approved these changes

2023-06-29 06:05 UTC, merged

2023-07-05 12:01 UTC, Junbo-Zheng commented
> @nowhszh Please update README.md too.

done #14